spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/achievement_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:sonoxie}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  aop:
    auto: true
    proxy-target-class: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 10MB
      # 单个文件的最大值
      max-file-size: 10MB
# MyBatis Mapper 扫描
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  